version: "3"
volumes:
  mongo-data:
networks:
  beers-infra:
    external: true
services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - beers-infra
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORTS=${POSTGRES_PORT_EXPOSE}
      - PGDATA=/postgres-data
    ports:
      - ${POSTGRES_PORTS}
